version: "3"

services:
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8800:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
